### ISSUE TITLE
Get ready for CRAN

### ISSUE THREAD

**Issue by padpadpadpad** [padpadpadpad/nls.multstart#5]
After the implementation of the updates suggested by @mathesong, I think the package should get submitted to CRAN. Just a single function it does a valuable job for the R community.

If only so that the package can start earning citation when me and my lab use it in the methods of our manuscripts! Free references are not to be missed. And it will also help publicise the package so people actually know about it!

Links for preparing a package for CRAN are from [Karl Broman](http://kbroman.org/pkg_primer/pages/cran.html), [Hadley Wickham](http://r-pkgs.had.co.nz/release.html) and [CRAN](https://cran.r-project.org/web/packages/policies.html)

**Comment by padpadpadpad** [comment]
Hi @mathesong, 

I have got a little bit of time this weekend so was going to prepare for a submission to CRAN. The package seems ready to go and I have fixed all notes and warnings across windows build (build_win), linux and Mac (Travis).

Just checking you are happy for me to do this? If we get it onto CRAN I can actually cite the package in my methods for papers! That would be exciting.

Cheers
Dan

**Comment by mathesong** [comment]
That would be awesome! I'm super on board! Would love to see what this
entails. I won't have much time to help this weekend though, but if it's
about ready to go already, then that's brilliant! I can maybe help out with
anything required next week.

Cheers,
G

On 3 Mar 2018 10:41, "Daniel Padfield" <notifications@github.com> wrote:

Hi @mathesong <https://github.com/mathesong>,

I have got a little bit of time this weekend so was going to prepare for a
submission to CRAN. The package seems ready to go and I have fixed all
notes and warnings across windows build (build_win), linux and Mac (Travis).

Just checking you are happy for me to do this? If we get it onto CRAN I can
actually cite the package in my methods for papers! That would be exciting.

Cheers
Dan

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/padpadpadpad/nls.multstart/issues/5#issuecomment-370134567>,
or mute the thread

**Comment by padpadpadpad** [comment]
Sweet! 

I am just going through the links posted in the first message on this thread. Have got the package down to no notes or warnings or errors which is the biggest step. Tested on Linux, Mac and Windows.

Suppose its just whether we want to put the README.md into a vignette or not. Not sure it is really necessary. Everything else is nearly done. Have updated the package version to 1.0.0 to make it seem like a big deal! 🤣

**Comment by padpadpadpad** [comment]
So I am going to submit around now. Have cleaned up everything and followed Hadley Wickham's recommendations. Lets see what happens!

**Comment by padpadpadpad** [comment]
Hi @mathesong,

Have heard back from CRAN.

> Thanks, please elaborate your description.
> 
> Please add a reference for the method in the 'Description' field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> with no space after 'doi:', 'arXiv:' and angle brackets for auto-linking.
> 

Out Description is currently "Robust non-linear regression using multiple starting points". Could change this to "Allows multiple start parameters for non-linear regression returning more robust fits".

It is a bit odd as most Description fields of the DESCRIPTION are all one line, and none of them include references (at least not that I can see by looking at DESCRIPTION files).

Not really sure what to put for the reference. I could put one of my papers but it is not a methods paper about the method.

What do you reckon? No other comments so I think thats positive. 😄 

Cheers
Dan

**Comment by padpadpadpad** [comment]
Had a bit of a look at other packages:

lme4: "Fit linear and generalized linear mixed-effects models. The models and their components are represented using S4 classes and methods.  The core computational algorithms are implemented using the 'Eigen' C++ library for numerical linear algebra and 'RcppEigen' "glue"."

nlstools: "Several tools for assessing the quality of fit of a gaussian nonlinear model are provided."

**Comment by padpadpadpad** [comment]
Thinking about this, maybe it is because the reviewer thinks the package is implementing a completely new algorithm... 

So how about:

"Robust non-linear least squares regression allowing multiple start parameters for nlsLM. Models are fitted with different start values and the best fitting model is chosen using AIC scores."

**Comment by padpadpadpad** [comment]
We are on CRAN. Badges added.

**Comment by mathesong** [comment]
Zomggggg!!!! This is amazing news! 🎉🎉🎉🎉
